name: Bulid with CMake

on:
  push:
    branches: [ master, github-actions-2 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        cmake_build_type: [Debug, RelWithDebInfo]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'usrsctp_source'
      
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.2
      with:
        github-api-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Prepare dirs
      shell: bash
      run: |
        mkdir -p cmake_build
        mkdir -p cmake_install
        
    - name: Generate CMake project
      shell: bash
      run: |
        cd cmake_build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} -DCMAKE_POSITION_INDEPENDENT_CODE=ON -Dsctp_build_programs=ON -Dsctp_build_fuzzer=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/cmake_install ${GITHUB_WORKSPACE}/usrsctp_source
        
    - name: Build and install project
      shell: bash
      run: |
        cmake --build cmake_build --config ${{ matrix.cmake_build_type }} --target install --clean-first
